services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres:alpine
    environment:
      POSTGRES_USER: hab
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  bsn-api:
    container_name: bsn-api
    image: habtamudires/bsn-api
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres

  bsn-ui:
    container_name: bsn-ui
    image: habtamudires/bsn-ui
    ports:
      - 8080:80
    networks:
      - spring-demo
    depends_on:
      - bsn-api

volumes:
  postgres:
    driver: local
networks:
  spring-demo:
    driver: bridge
