server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: hab
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host:  localhost #${EMAIL_HOST_NAME}
    port: 1025 #465
    username: hab #${EMAIL_USER_NAME}
    password: password #${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9090/realms/book-social-network"
application:
  cors:
    origins: http://localhost:4200,http://localhost:8080
  file:
    upload:
      picture-output-path: ./uploads