server:
  port: 8088
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: hab
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    user: hab
    password: password
    properties:
      mail:
        smtp:
          trust: "*"
        oauth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: oi9zj1PxGawOWOftX6xmut0C6mlXQOkt34QYcBtZrQ53py0LTNrBirsy8x/VLgU+
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      picture-output-path: ./uploads